services:
    K3ssen\VueBundle\Storage\VueDataStorage:
        autoconfigure: true

    K3ssen\VueBundle\Twig\VueExtension:
        autoconfigure: true
        arguments:
            $vueDataStorage: '@K3ssen\VueBundle\Storage\VueDataStorage'

    K3ssen\VueBundle\Form\Extension\VueFormTypeExtension:
        autoconfigure: true
        arguments:
            $vueDataStorage: '@K3ssen\VueBundle\Storage\VueDataStorage'
        tags:
            - 'form.type_extension'